project_id = "qjoyyevmdfbdcbhekisy"

[functions.chat-assistant]
verify_jwt = false

[functions.processar-comprovativo]
verify_jwt = true

[functions.agregar-vagas]
verify_jwt = false

[functions.scraper-angovagas]
verify_jwt = false

[functions.enviar-notificacao]
verify_jwt = false

[functions.desativar-vagas-expiradas]
verify_jwt = false

[functions.inserir-vagas-manuais]
verify_jwt = false